server:
  port: 9191
  servlet:
    context-path: /mdrt-test/api

spring:
  application:
    name: MDRT
  web:
    resources:
      static-locations: classpath:/static/
    mvc:
      static-path-pattern: /**